const products = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Aldebaran',
    category: 'be-e-e',
    price: 230,
    unit: "piece",
    discount_price: "no discount",
    description: "Sweat dry meat with spices",
    img: "",
    available: true,
    favourite: false,
    archived: false,
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec34736442a',
    name: 'Sosiska',
    category: 'be-e-e',
    price: 150,
    unit: "kg",
    discount_price: "no discount",
    description: "Sosiska est sosiska",
    img: "",
    available: true,
    favourite: true,
    archived: false,
  },
  {
    id: '3958621e-712f-4377-85e9-fec4b6a6442a',
    name: 'Свинячи ушки',
    category: 'Хрю-хрю',
    price: 190,
    unit: "кг",
    discount_price: "no discount",
    description: "Ушки свинки в специях",
    img: "",
    available: true,
    favourite: false,
    archived: false,
  },
  {
    id: '3958dc9e-712f-1111-85e9-fec75116442a',
    name: 'Хрюшкин пятак',
    category: 'Хрю-хрю',
    price: 80,
    unit: "piece",
    discount_price: "no discount",
    description: "Пятак как пятак",
    img: "",
    available: true,
    favourite: false,
    archived: false,
  },
  {
    id: '3950000e-712f-4377-85e9-fec4b6a6442a',
    name: 'Курочка',
    category: 'Кукареку',
    price: 177,
    unit: "кг",
    discount_price: "no discount",
    description: "Курочка в маринаде для мангала",
    img: "",
    available: true,
    favourite: true,
    archived: false,
  }
]

  module.exports = { products };
